- hosts: all
  vars:
    deploy_folder: /home/ubuntu/scaneat/scaneat-web

  tasks:
  - name: Copy files to the server
    synchronize:
      src: ../../dist/
      dest: "{{ deploy_folder }}"
      rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
